/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#f7f9fb",
        "tertiary-container": "#0b1c30",
        error: "#ba1a1a",
        "primary-fixed": "#dae2fd",
        "on-surface": "#191c1e",
        "on-secondary-fixed-variant": "#003ea8",
        "secondary-fixed-dim": "#b4c5ff",
        "surface-container": "#eceef0",
        "surface-tint": "#565e74",
        "surface-dim": "#d8dadc",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#00174b",
        outline: "#76777d",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed": "#0b1c30",
        "on-tertiary-fixed-variant": "#38485d",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "secondary-fixed": "#dbe1ff",
        "primary-container": "#131b2e",
        "on-primary-fixed": "#131b2e",
        "on-secondary-container": "#fefcff",
        "on-error": "#ffffff",
        "on-primary-container": "#7c839b",
        "tertiary-fixed-dim": "#b7c8e1",
        "inverse-surface": "#2d3133",
        "on-surface-variant": "#45464d",
        primary: "#000000",
        tertiary: "#000000",
        "surface-variant": "#e0e3e5",
        "inverse-on-surface": "#eff1f3",
        "on-primary-fixed-variant": "#3f465c",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#bec6e0",
        "surface-bright": "#f7f9fb",
        "on-background": "#191c1e",
        "error-container": "#ffdad6",
        "outline-variant": "#c6c6cd",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#bec6e0",
        "on-tertiary-container": "#75859d",
        "tertiary-fixed": "#d3e4fe",
        secondary: "#0051d5",
        "secondary-container": "#316bf3",
        background: "#f7f9fb"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "section-gap": "32px",
        unit: "4px",
        "stack-md": "16px",
        "container-padding": "24px",
        "stack-sm": "8px",
        gutter: "16px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "table-data": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "title-sm": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
