version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - ./tox21_production_models:/app/tox21_production_models
    restart: always