version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      TOX21_MODELS_DIR: /app/tox21_production_models
    ports:
      - "8010:8000"
    volumes:
      - ./tox21_production_models:/app/tox21_production_models
    restart: always