import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowRight, Database, Activity, Target, Code, Sliders, Cpu, ShieldCheck, ChevronDown, Terminal, CheckCircle2, FlaskConical, ExternalLink } from 'lucide-react';
import StructureViewer3D from '../components/StructureViewer3D';

export default function Home() {
  const navigate = useNavigate();
  const [apiTab, setApiTab] = useState('curl'); // 'curl' | 'python' | 'js'
  const [activeFaq, setActiveFaq] = useState(null);
  const siteUrl = (import.meta.env.VITE_SITE_URL || window.location.origin).replace(/\/$/, '');
  const apiBase = (import.meta.env.VITE_API_BASE_URL || 'https://api-tox.loca.lt').replace(/\/$/, '');
  const apiDocsUrl = `${apiBase}/docs`;
  const exampleApiBase = apiBase;

  const handleQuickMolecule = (smiles) => {
    navigate('/predict', { state: { smiles } });
  };

  const toggleFaq = (index) => {
    setActiveFaq(activeFaq === index ? null : index);
  };

  const codeTemplates = {
    curl: `curl -X POST "${exampleApiBase}/predict" \\
     -H "Content-Type: application/json" \\
     -d '{"smiles": ["CC(=O)OC1=CC=CC=C1C(=O)O"]}'`,
    python: `import requests

url = "${exampleApiBase}/predict"
payload = {"smiles": ["CC(=O)OC1=CC=CC=C1C(=O)O"]}
response = requests.post(url, json=payload).json()

print(response["results"][0]["predictions"])`,
    js: `const fetchPredictions = async (smiles) => {
  const res = await fetch("${exampleApiBase}/predict", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ smiles: [smiles] })
  });
  const data = await res.json();
  return data.results[0].predictions;
};

fetchPredictions("CC(=O)OC1=CC=CC=C1C(=O)O").then(console.log);`
  };

  const faqs = [
    {
      q: "What is the source of the training data?",
      a: "Our consensus classifiers are trained on the Tox21 (Toxicology in the 21st Century) dataset. This dataset was generated by screening library compounds against 12 high-throughput assays measuring key nuclear receptor (NR) and stress response (SR) pathway activations."
    },
    {
      q: "How does the Consensus Ensemble calculate predictions?",
      a: "Instead of relying on a single classifier, we combine two distinct models: Bernoulli Naive Bayes (tuned for sparse binary vectors) and XGBoost (optimized for complex structural bit interactions). The final consensus score is a weighted probability calculated as: Consensus = w₁·NB + w₂·XGBoost, with weights optimized directly via validation ROC-AUC."
    },
    {
      q: "Why don't you use a standard 0.50 threshold cutoff?",
      a: "Tox21 screens are highly imbalanced, often containing fewer than 1% active hits. A flat 0.50 cutoff leads to high specificity but near-zero sensitivity. We search validation thresholds between 0.10 and 0.95 to select the exact threshold that maximizes the Matthews Correlation Coefficient (MCC), balancing active and inactive classification."
    },
    {
      q: "How can I integrate these models into my own pipeline?",
      a: "We expose standard REST endpoints via our FastAPI backend. You can use our POST /predict endpoint to batch evaluate SMILES queries or get structural visuals using our GET /structure (2D SVG) and GET /structure3d (conformer-optimized SDF blocks) endpoints."
    }
  ];

  return (
    <div className="w-full flex flex-col items-center relative overflow-hidden bg-slate-50/30">
      {/* Background Molecular Roots "holding the page" */}
      <img src="/molecular_roots.png" alt="Molecular Roots Right" className="absolute right-[-100px] top-[550px] w-[500px] md:w-[700px] lg:w-[900px] opacity-[0.09] pointer-events-none z-0 select-none" />
      <img src="/molecular_roots.png" alt="Molecular Roots Left" className="absolute left-[-200px] top-[1300px] w-[500px] md:w-[700px] lg:w-[800px] opacity-[0.09] pointer-events-none z-0 select-none scale-x-[-1]" />
      {/* Hero Section with Video Background */}
      <section className="relative w-full min-h-[calc(100vh-4rem)] flex items-center justify-center px-4 sm:px-6 lg:px-12 py-10 sm:py-12 lg:py-16 overflow-hidden">
        {/* Background Video */}
        <video 
          autoPlay 
          loop 
          muted 
          playsInline 
          className="absolute inset-0 w-full h-full object-cover z-0"
        >
          <source src="/bg.mp4" type="video/mp4" />
          Your browser does not support the video tag.
        </video>
        
        {/* Soft Premium Light Overlay (low opacity to let the video shine clearly) */}
        <div className="absolute inset-0 bg-gradient-to-b from-white/10 via-white/5 to-slate-50/20 z-10" />

        {/* Content Wrapper */}
        <div className="relative max-w-7xl mx-auto w-full grid grid-cols-1 lg:grid-cols-2 gap-8 lg:gap-12 items-center z-20">
          <div className="space-y-5 sm:space-y-6 bg-white/78 backdrop-blur-md p-5 sm:p-7 lg:p-10 rounded-2xl border border-slate-250/80 shadow-lg text-center lg:text-left">
            <span className="px-3.5 py-1 bg-indigo-50 text-indigo-750 text-[10px] sm:text-xs font-mono font-bold rounded-full border border-indigo-100 flex items-center gap-1.5 w-fit shadow-sm mx-auto lg:mx-0">
              <span className="w-1.5 h-1.5 rounded-full bg-indigo-600 animate-pulse"></span>
              Tox21 High-Throughput Screening Portal
            </span>
            <h1 className="text-3xl sm:text-4xl lg:text-6xl font-extrabold tracking-tight text-slate-900 leading-tight">
              Consensus ML <br />
              <span className="text-indigo-650">Toxicity Prediction</span>
            </h1>
            <p className="text-slate-650 text-sm sm:text-base leading-relaxed max-w-lg mx-auto lg:mx-0">
              Evaluate chemical compounds across 12 critical biological endpoints targeting nuclear receptor activations and stress response pathways. Serves robust, consensus machine learning predictions using Morgan fingerprints and optimized thresholds.
            </p>
            <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3 sm:gap-4 pt-2 max-w-xl mx-auto lg:mx-0">
              <button
                onClick={() => navigate('/predict')}
                className="bg-indigo-600 hover:bg-indigo-700 text-white px-5 sm:px-6 py-3.5 sm:py-4 font-bold rounded-xl transition-all flex items-center justify-center gap-2 shadow-md hover:shadow-lg active:scale-95 hover:scale-[1.01] w-full sm:w-auto"
              >
                <span>Launch Predictor</span>
                <ArrowRight className="w-4 h-4" />
              </button>
              <button
                onClick={() => navigate('/docs')}
                className="bg-white border border-slate-200 hover:bg-slate-50 text-slate-700 px-5 sm:px-6 py-3.5 sm:py-4 font-bold rounded-xl transition-all shadow-sm active:scale-95 w-full sm:w-auto"
              >
                Methodology Docs
              </button>
            </div>
          </div>
          
          {/* Interactive 3D Hero Structure */}
          <div className="w-full max-w-sm sm:max-w-md mx-auto lg:ml-auto flex flex-col gap-2">
            <div className="aspect-square w-full rounded-2xl overflow-hidden border border-slate-200 shadow-xl relative group bg-white p-2 sm:p-3">
              <div className="absolute top-3 left-3 sm:top-4 sm:left-4 bg-white/90 backdrop-blur-sm border border-slate-200/80 px-2.5 py-1 rounded-lg text-[9px] sm:text-[10px] font-mono text-slate-600 z-10 shadow-sm flex items-center gap-1.5 max-w-[calc(100%-1.5rem)] sm:max-w-none">
                <FlaskConical className="w-3.5 h-3.5 text-indigo-600 animate-pulse" />
                <span className="truncate">Interactive 3D Preview (Caffeine)</span>
              </div>
              <StructureViewer3D smiles="CN1C=NC2=C1C(=O)N(C(=O)N2C)C" />
            </div>
            <span className="text-[10px] text-center text-slate-500 font-mono px-2">
              Drag to rotate • Scroll to zoom 
            </span>
          </div>
        </div>
      </section>

      {/* Trust & Integrations Banner */}
      <section className="w-full bg-slate-50 border-y border-slate-200/80 py-7 sm:py-8 px-4 sm:px-6 lg:px-12 z-20">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4 sm:gap-6 text-center md:text-left">
          <span className="text-xs font-bold text-slate-450 uppercase tracking-widest font-mono">Screening Standards</span>
          <div className="flex flex-wrap items-center justify-center gap-4 sm:gap-6 md:gap-12 text-xs sm:text-sm font-semibold text-slate-400 font-mono">
            <span className="hover:text-slate-650 transition-colors">Tox21 Consortium</span>
            <span className="hover:text-slate-650 transition-colors">NIH / NCATS</span>
            <span className="hover:text-slate-650 transition-colors">US EPA</span>
            <span className="hover:text-slate-650 transition-colors">RDKit core</span>
            <span className="hover:text-slate-650 transition-colors">FDA compliant</span>
          </div>
        </div>
      </section>

      {/* Bento Grid Features Section */}
      <section className="w-full max-w-7xl px-4 sm:px-6 lg:px-12 py-16 sm:py-20 space-y-10 sm:space-y-12">
        <div className="text-center max-w-xl mx-auto space-y-2">
          <h2 className="text-2xl sm:text-3xl font-black text-slate-900 tracking-tight">Consensus Pipeline Architecture</h2>
          <p className="text-xs sm:text-sm text-slate-500">Advanced featurization, double-stage reduction, and optimized decision logic.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
          <div className="bg-white border border-slate-200 p-6 rounded-2xl text-left space-y-4 hover:border-indigo-500/40 hover:shadow-md transition-all shadow-sm">
            <div className="w-10 h-10 rounded-xl bg-indigo-50 border border-indigo-100 flex items-center justify-center text-indigo-650">
              <Code className="w-5 h-5" />
            </div>
            <h3 className="font-bold text-base text-slate-900">Morgan Fingerprints</h3>
            <p className="text-xs text-slate-600 leading-relaxed">
              Chemical SMILES are encoded into fixed-length 1024-bit Morgan ECFP4 fingerprint vectors using RDKit.
            </p>
          </div>
          <div className="bg-white border border-slate-200 p-6 rounded-2xl text-left space-y-4 hover:border-indigo-500/40 hover:shadow-md transition-all shadow-sm">
            <div className="w-10 h-10 rounded-xl bg-indigo-50 border border-indigo-100 flex items-center justify-center text-indigo-650">
              <Sliders className="w-5 h-5" />
            </div>
            <h3 className="font-bold text-base text-slate-900">Feature Selection</h3>
            <p className="text-xs text-slate-600 leading-relaxed">
              Applies double-stage reduction (variance thresholding + Random Forest selection) to extract sparse toxicophores.
            </p>
          </div>
          <div className="bg-white border border-slate-200 p-6 rounded-2xl text-left space-y-4 hover:border-indigo-500/40 hover:shadow-md transition-all shadow-sm">
            <div className="w-10 h-10 rounded-xl bg-indigo-50 border border-indigo-100 flex items-center justify-center text-indigo-650">
              <Cpu className="w-5 h-5" />
            </div>
            <h3 className="font-bold text-base text-slate-900">Consensus Ensembling</h3>
            <p className="text-xs text-slate-600 leading-relaxed">
              Combines Naive Bayes and XGBoost predictions using model-specific weights optimized by validation ROC-AUC.
            </p>
          </div>
          <div className="bg-white border border-slate-200 p-6 rounded-2xl text-left space-y-4 hover:border-indigo-500/40 hover:shadow-md transition-all shadow-sm">
            <div className="w-10 h-10 rounded-xl bg-indigo-50 border border-indigo-100 flex items-center justify-center text-indigo-650">
              <ShieldCheck className="w-5 h-5" />
            </div>
            <h3 className="font-bold text-base text-slate-900">Optimal Thresholds</h3>
            <p className="text-xs text-slate-600 leading-relaxed">
              Instead of a flat 0.50 cutoff, predictions utilize dynamic thresholds tuned to maximize MCC on imbalanced screens.
            </p>
          </div>
        </div>
      </section>

      {/* High-Throughput Consensus Diagnostics Section */}
      <section className="w-full max-w-7xl px-4 sm:px-6 lg:px-12 py-16 sm:py-20 grid grid-cols-1 lg:grid-cols-12 gap-8 sm:gap-12 items-center z-10">
        <div className="lg:col-span-6 rounded-2xl overflow-hidden border border-slate-200 shadow-md bg-white p-3">
          <img src="/tox21_diagnostic.png" alt="Toxicity Screening Diagnostic" className="w-full h-auto rounded-xl object-cover hover:scale-[1.01] transition-transform" />
        </div>
        <div className="lg:col-span-6 space-y-6">
          <span className="px-3.5 py-1 bg-emerald-50 text-emerald-700 text-xs font-mono font-bold rounded-full border border-emerald-100 flex items-center gap-1.5 w-fit shadow-sm">
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse"></span>
            High-Throughput Assay Screens
          </span>
          <h2 className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight leading-tight">
            High-Throughput Consensus <br />
            <span className="text-indigo-650">Toxicity Diagnostics</span>
          </h2>
          <p className="text-slate-650 text-sm sm:text-base leading-relaxed">
            Consensus machine learning models map circular Morgan ECFP4 descriptors against target biological pathways. By identifying key toxicophores and molecular structures, the system alerts researchers to potential endocrine disruptions and cellular stressors.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs font-mono text-slate-500">
            <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-xl">
              <span className="block text-[10px] uppercase font-bold text-indigo-650 mb-1">Accuracy Benchmark</span>
              <span className="font-semibold text-slate-800 text-sm">0.824 mean ROC-AUC</span>
            </div>
            <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-xl">
              <span className="block text-[10px] uppercase font-bold text-indigo-650 mb-1">Evaluation Class</span>
              <span className="font-semibold text-slate-800 text-sm">12 biological assays</span>
            </div>
          </div>
        </div>
      </section>

      {/* Preset Compounds Grid */}
      <section className="w-full bg-slate-50 border-y border-slate-200/80 py-16 px-12 z-10">
        <div className="max-w-7xl mx-auto space-y-8">
          <div className="text-center space-y-1">
            <h2 className="text-2xl font-black text-slate-900">Quick Test Presets</h2>
            <p className="text-xs text-slate-500">Click any preset molecule to load it straight into the Predictor panel and evaluate predictions.</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4">
            {[
              { name: "Aspirin", desc: "Safe Control (Salicylic acid derivative)", smiles: "CC(=O)OC1=CC=CC=C1C(=O)O" },
              { name: "Caffeine", desc: "CNS Stimulant (Xanthine alkaloid)", smiles: "CN1C=NC2=C1C(=O)N(C(=O)N2C)C" },
              { name: "Bisphenol A", desc: "Endocrine Disruption example", smiles: "CC(C)(C1=CC=C(C=C1)O)C2=CC=C(C=C2)O" },
              { name: "Benzo[a]pyrene", desc: "Carcinogenic Polycyclic Aromatic", smiles: "C1=CC=C2C(=C1)C=CC3=C2C=CC4=C3C=CC5=C4C=CC5" }
            ].map((preset) => (
              <button
                key={preset.name}
                onClick={() => handleQuickMolecule(preset.smiles)}
                className="p-5 bg-white border border-slate-200 rounded-xl hover:border-indigo-500 text-left space-y-2 hover:shadow-md transition-all group hover:scale-[1.02]"
              >
                <h3 className="font-bold text-sm text-slate-900 group-hover:text-indigo-650">{preset.name}</h3>
                <p className="text-[11px] text-slate-500 leading-relaxed h-10 overflow-hidden">{preset.desc}</p>
                <span className="text-[10px] text-indigo-600 font-bold block pt-2 group-hover:underline">Analyze SMILES →</span>
              </button>
            ))}
          </div>
        </div>
      </section>

      {/* Developer API Section */}
      <section className="w-full max-w-7xl px-12 py-20 grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
        <div className="lg:col-span-5 space-y-6">
          <span className="px-3 py-1 bg-indigo-50 text-indigo-750 text-xs font-mono font-bold rounded-full border border-indigo-100 w-fit flex items-center gap-1">
            <Terminal className="w-3.5 h-3.5" />
            Exposed REST Interfaces
          </span>
          <h2 className="text-3xl font-extrabold text-slate-900 tracking-tight">
            Developer API <br />
            Integration
          </h2>
          <p className="text-slate-650 text-xs leading-relaxed">
            Connect Tox21 consensus calculations straight into your chemical databases or machine learning notebooks. Supports batch structures scoring, structure 2D SVGs vectors, and optimized 3D conformers MOL coordinates.
          </p>
          <div className="space-y-3.5 text-xs text-slate-600">
            <div className="flex items-center gap-2.5">
              <CheckCircle2 className="w-4 h-4 text-emerald-600" />
              <span>FastAPI architecture with auto-documentation (Swagger UI)</span>
            </div>
            <div className="flex items-center gap-2.5">
              <CheckCircle2 className="w-4 h-4 text-emerald-600" />
              <span>Low-latency scoring (mean ~140ms per compound)</span>
            </div>
            <div className="flex items-center gap-2.5">
              <CheckCircle2 className="w-4 h-4 text-emerald-600" />
              <span>CORS enabled for custom web applications</span>
            </div>
          </div>
          <button 
            onClick={() => window.open(apiDocsUrl, '_blank')}
            className="text-xs font-bold text-indigo-650 flex items-center gap-1.5 hover:underline pt-2"
          >
            <span>Open Swagger Docs</span>
            <ExternalLink className="w-3.5 h-3.5" />
          </button>
        </div>

        {/* Stateful Code Panel */}
        <div className="lg:col-span-7 bg-slate-900 rounded-2xl overflow-hidden shadow-xl border border-slate-800">
          <div className="flex bg-slate-950 border-b border-slate-800 p-2 justify-between items-center">
            <div className="flex gap-2">
              <button 
                onClick={() => setApiTab('curl')}
                className={`px-3 py-1.5 rounded text-xs font-mono transition-all ${apiTab === 'curl' ? 'bg-indigo-600 text-white font-bold' : 'text-slate-400 hover:text-slate-100'}`}
              >
                cURL
              </button>
              <button 
                onClick={() => setApiTab('python')}
                className={`px-3 py-1.5 rounded text-xs font-mono transition-all ${apiTab === 'python' ? 'bg-indigo-600 text-white font-bold' : 'text-slate-400 hover:text-slate-100'}`}
              >
                Python
              </button>
              <button 
                onClick={() => setApiTab('js')}
                className={`px-3 py-1.5 rounded text-xs font-mono transition-all ${apiTab === 'js' ? 'bg-indigo-600 text-white font-bold' : 'text-slate-400 hover:text-slate-100'}`}
              >
                NodeJS
              </button>
            </div>
            <span className="text-[10px] text-slate-500 font-mono pr-2">POST /predict</span>
          </div>
          <div className="p-6 overflow-x-auto">
            <pre className="text-xs text-indigo-200 font-mono whitespace-pre">{codeTemplates[apiTab]}</pre>
          </div>
        </div>
      </section>

      {/* Stateful FAQ Accordion Section */}
      <section className="w-full bg-slate-50 border-t border-slate-200/80 py-20 px-12">
        <div className="max-w-3xl mx-auto space-y-12">
          <div className="text-center space-y-2">
            <h2 className="text-3xl font-extrabold text-slate-900 tracking-tight">Frequently Asked Questions</h2>
            <p className="text-xs text-slate-500">Methodology details, classification logic, and structural descriptors.</p>
          </div>

          <div className="space-y-3">
            {faqs.map((faq, index) => {
              const isOpen = activeFaq === index;
              return (
                <div 
                  key={index}
                  className="bg-white border border-slate-200 rounded-xl overflow-hidden transition-all shadow-sm"
                >
                  <button
                    onClick={() => toggleFaq(index)}
                    className="w-full px-6 py-4 flex items-center justify-between text-left hover:bg-slate-50/50 transition-colors"
                  >
                    <span className="font-bold text-sm text-slate-900">{faq.q}</span>
                    <ChevronDown className={`w-4 h-4 text-slate-400 transition-transform ${isOpen ? 'rotate-180' : ''}`} />
                  </button>
                  {isOpen && (
                    <div className="px-6 pb-5 pt-1 border-t border-slate-100 text-xs text-slate-650 leading-relaxed">
                      {faq.a}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      </section>
    </div>
  );
}
