name: Deploy FastAPI to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'tox-api/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./tox-api

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: toxapiayman.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          # Use the unique GitHub commit hash to bust the Azure Cache
          docker build -t toxapiayman.azurecr.io/tox-backend:${{ github.sha }} .
          docker push toxapiayman.azurecr.io/tox-backend:${{ github.sha }}

      - name: Deploy to Azure Container Instances
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az container create \
              --resource-group tox-api-rg-italy \
              --name tox-api-container \
              --image toxapiayman.azurecr.io/tox-backend:${{ github.sha }} \
              --registry-username ${{ secrets.ACR_USERNAME }} \
              --registry-password ${{ secrets.ACR_PASSWORD }} \
              --dns-name-label tox-api-ayman \
              --ports 7860 \
              --os-type Linux \
              --cpu 1 \
              --memory 1.5 \
              --location italynorth